export const REQUEST_FEED_DATA = "REQUEST_FEED_DATA";
export const RECEIVE_FEED_DATA = "RECEIVE_FEED_DATA";

export const GET_DEVICE_LOC_DATA = "GET_DEVICE_LOC_DATA";

export const GET_DEVICE_GEOCODE_DATA = "GET_DEVICE_GEOCODE_DATA";

export const REQUEST_USER_DATA = "REQUEST_USER_DATA";
export const RECEIVE_USER_DATA = "RECEIVE_USER_DATA";

export const REQUEST_WEATHER_DATA = "REQUEST_WEATHER_DATA";
export const RECEIVE_WEATHER_DATA = "RECEIVE_WEATHER_DATA";
